name: Build yocto image

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container
    container:
      image: initdc/thead-yocto:latest
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun
    defaults:
      run:
        working-directory: /home/ubuntu
    steps:
      - name: Prepare package
        run: sudo apt-get update && sudo apt-get install -y git ruby ccache
      - name: Checkout
        run: |
          git clone --depth 1 https://github.com/initdc/LicheePi4A.git workdir
          cd workdir
          git submodule update --init --recursive --depth 1 external/thead-yocto/xuantie-yocto
      - name: Prepare scripts deps
        run: |
          gem install bundler
          cd workdir/scripts && bundle install
      - name: Build release
        run: cd workdir && ruby scripts/ci_yocto.rb
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: "workdir/upload/*"
      - name: Upload to Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "workdir/upload/*"
